export const ACTION_TYPE = 'ACTION_TYPE'

// user list
export const USER_LIST_REQUEST = 'USER_LIST_REQUEST'
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS'
export const USER_LIST_FAILURE = 'USER_LIST_FAILURE'

// freind list
export const FRIEND_LIST_REQUEST = 'FRIEND_LIST_REQUEST'
export const FRIEND_LIST_SUCCESS = 'FRIEND_LIST_SUCCESS'
export const FRIEND_LIST_FAILURE = 'FRIEND_LIST_FAILURE'

// select friend
export const SELECT_FRIEND = 'SELECT_FRIEND'

// chat
export const PEER_RECEIVE_REQUEST = 'PEER_RECEIVE_REQUEST'
export const PEER_RECIEVE_SUCCESS = 'PEER_RECIEVE_SUCCESS'
export const PEER_RECIEVE_FAILURE = 'PEER_RECIEVE_SUCCESS'

export const PEER_SEND_REQUEST = 'PEER_SEND_REQUEST'
export const PEER_SEND_SUCCESS = 'PEER_SEND_SUCCESS'
export const PEER_SEND_FAILURE = 'PEER_SEND_FAILURE'

export const SAVE_CHAT_REQUEST = 'SAVE_CHAT_REQUEST'
export const SAVE_CHAT_SUCCESS = 'SAVE_CHAT_SUCCESS'
export const SAVE_CHAT_FAILURE = 'SAVE_CHAT_FAILURE'

export const GET_CHAT_HISTORY_REQUEST = 'GET_CHAT_HISTORY_REQUEST'
export const GET_CHAT_HISTORY_SUCCESS = 'GET_CHAT_HISTORY_SUCCESS'
export const GET_CHAT_HISTORY_FAILURE = 'GET_CHAT_HISTORY_FAILURE'

